info:
  app:
    name: server-quartz
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mariaDB
    type: com.alibaba.druid.pool.DruidDataSource